### ISSUE TITLE
Any further development?

### ISSUE THREAD

**Issue by t69broken** [cedarrapidsboy/pms-postprocessing#15]
First off would like to say, I'm so happy to have come across this. Was pulling my hair out before I found it.

To my question, any way to change the container of the saved files?  I just have more luck with mp4 or mkv playing through plex. TS containers are laggy.

**Comment by cedarrapidsboy** [comment]
It's been a long time since I looked at this. I'll pop it into my server to see if it is still working as intended.
If it is doing anything useful... it should be, by default, transcoding to an MP4 file (or MKV if specified with the PPFORMAT variable).

PPFORMAT - Output file format. Either 'mp4' or 'mkv'. 'mp4' supports FFMPEG faststart flag. (default: 'mp4')

**Comment by cedarrapidsboy** [comment]
I added this script back to my Plex server and can confirm that it processed the morning news and saved it as MP4. So, to answer your question, yes. This script's default behaviour will recompress and remux the TS recordings to MP4.
